name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  commitlint:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and cache yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Validate commit messages
        if: github.event_name == 'push'
        run: yarn commitlint --from=${{ github.event.before }} --to=${{ github.sha }} --verbose

      - name: Validate PR title
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.pull_request.title }}" | yarn commitlint --verbose

  format-check:
    name: Check Files Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Aztec version
        id: aztec-version
        run: |
          AZTEC_VERSION=$(node -p "require('./package.json').config.aztecVersion")
          echo "version=$AZTEC_VERSION" >> "$GITHUB_OUTPUT"
          echo "Aztec version is $AZTEC_VERSION" 

      - name: Install Aztec CLI
        run: |
          curl -s https://install.aztec.network > tmp.sh
          VERSION=${{ steps.aztec-version.outputs.version }} bash tmp.sh <<< yes "yes"

      - name: Update path
        run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check Noir formatting
        run: aztec-nargo fmt --check

      - name: Check Javascript & Typescript formatting
        run: yarn prettier '**/*.{js,ts}' --check 